#!/usr/bin/env bash
#Create a new Nginx with new server

if ! nginx -v; then
sudo apt-get update
sudo apt-get install -y nginx
fi

# setup home
echo "Hello World!" | sudo tee /var/www/html/index.html

# setup redirect
replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me \/ permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# setting up 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement/" /etc/nginx/sites-enabled/default

ufw allow 'NGINX Full'
# restart the server
sudo service nginx restart
