#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo servix nginx status
sudo service nginx start
netstat -lpn
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
