#!/usr/bin/env bash
# Your script should only display:

# username
# user id
# Home directory path for the user
# Requirements:

# You must use the while loop (for and until are forbidden)

FILE="/etc/passwd"

while read -r line
do
echo "$line" | cut -d":" -f1,3,6
done < "$FILE"
