#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:

# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
# Requirements:

# You must use the while loop (for and until are forbidden)
# You must use the if, elif and else statements
i=1

while ((i < 11)); do
if [ $i -eq 4 ]; then
echo "bad luck"
elif [ $i -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
