#!/usr/bin/env bash
# web debugging, nginx running as nginx
# 1 set user in config
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# 2 add 8080 for nginx
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# 3 set permisssions so only user can edit config
chmod 644 /etc/nginx/nginx.conf
# terminate apache
pkill apache2
# restart nginx
sudo -u nginx service nginx start
