#!/usr/bin/env bash
# that creates an RSA key pair.

# Requirements:

# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

ssh-keygen -b 4096 -P betty -f school
